- name: Provisionar Estação de Desenvolvimento Completa (Arch + i3 + Mise + Flatpak)
  hosts: localhost
  connection: local
  # Removi o become global para evitar problemas com o path ~/
  
  tasks:
    - name: 1. Instalar pacotes base via Pacman
      become: yes # Root apenas aqui
      community.general.pacman:
        name:
          - ttf-jetbrains-mono-nerd
          - noto-fonts-emoji
          - i3-wm
          - polybar
          - firefox
          - picom
          - rofi
          - alacritty
          - feh
          - zsh
          - git
          - base-devel
          - neovim
          - code
          - mise
          - flatpak
          - bluez
          - bluez-utils
          - blueman
          - pavucontrol
          - maim
          - xclip
          - slop
          - gnome-keyring
        state: present
        update_cache: yes

    - name: 2. Configurar Repositório Flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: 3. Instalar Discord via Flatpak
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub
    
    - name: 4. Criar estrutura de diretórios config
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "~/.config/i3"
        - "~/.config/polybar"
        - "~/.config/nvim"
        - "~/.config/picom"
        - "~/.local/bin"
        - "~/.screenlayout"

    - name: 5. Sincronizar Dotfiles
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: 'dotfiles/i3_config', dest: '~/.config/i3/config' }
        - { src: 'dotfiles/polybar_config.ini', dest: '~/.config/polybar/config.ini' }
        - { src: 'dotfiles/picom.conf', dest: '~/.config/picom/picom.conf' }

    - name: 6. Configurar ativação do Mise no ZSH
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(mise activate zsh)"'
        create: yes
        state: present

    - name: 7. Instalar linguagens globais via Mise
      shell: |
        eval "$($HOME/.local/bin/mise activate zsh)"
        mise use --global rust@latest
        mise use --global node@latest
      args:
        executable: /usr/bin/zsh
        creates: ~/.local/share/mise/installs/node

    - name: 8. Activar serviço Bluetooth
      become: yes
      systemd:
        name: bluetooth
        enabled: yes
        state: started

    - name: 9. Configurar Layout de Teclado PT-BR
      become: yes
      command: localectl set-x11-keymap br
      changed_when: false
