- name: Provisionar Estação de Desenvolvimento Completa (Arch + i3 + Mise + Flatpak)
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: 1. Instalar pacotes base via Pacman
      community.general.pacman:
        name:
          - i3-wm
          - polybar
	  - firefox
          - picom
          - rofi
          - alacritty
          - feh
          - zsh
          - git
          - base-devel
          - neovim
          - code
          - mise           # Gestor de linguagens (Rust, Node, etc.)
          - flatpak        # Para aplicações isoladas como o Discord
          - bluez
          - bluez-utils
          - blueman
          - pavucontrol
          - maim           # Screenshots
          - xclip          # Clipboard
  	  - slop
          - gnome-keyring  # Para salvar sessões (Discord)
        state: present
        update_cache: yes

    - name: 2. Configurar Repositório Flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: 3. Instalar Discord via Flatpak
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub
	
    - name: 4. Criar estrutura de diretórios config
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config/i3
        - ~/.config/polybar
        - ~/.config/nvim
        - ~/.config/picom # Adicionado aqui para não dar erro no copy
        - ~/.local/bin
        - ~/.screenlayout

    - name: 5. Sincronizar Dotfiles
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: 'dotfiles/i3_config', dest: '~/.config/i3/config' }
        - { src: 'dotfiles/polybar_config.ini', dest: '~/.config/polybar/config.ini' }
        - { src: 'dotfiles/picom.conf', dest: '~/.config/picom/picom.conf' }

    - name: 6. Configurar ativação do Mise no ZSH
      lineinfile:
        path: ~/.zshrc
        line: 'eval "$(mise activate zsh)"'
        create: yes
        state: present

    - name: 7. Instalar linguagens globais via Mise
      shell: |
        eval "$(~/.local/bin/mise activate zsh)"
        mise use --global rust@latest
        mise use --global node@latest
      args:
        executable: /usr/bin/zsh
        creates: ~/.local/share/mise/installs/node # Evita rodar se já existir

    - name: 8. Activar serviço Bluetooth
      become: yes # Necessário para systemd
      systemd:
        name: bluetooth
        enabled: yes
        state: started

    - name: 9. Configurar Layout de Teclado PT-BR
      become: yes # Necessário para alterar config de sistema
      command: localectl set-x11-keymap br
      changed_when: false # Comando informativo/configuração simples
